### ISSUE TITLE
Sorting icon messes with layout

### ISSUE THREAD

**Issue by lcfg** [diepes/sorttable.js#1]
The sorting icon that is being added in `THEAD` cells of the table messes up the layout. You can fix this by adding the following css:

``` css
#sorttable_sortfwdind1, #sorttable_sortrevind1 {
position: absolute;
}
```

Not entirely sure if this has any negative side effects, but it looks much better on my end.

Edit: this requires that the table has `position: relative` set.
